# Pandas Accessing Data

In [2]:
!pip install datasets

Requirement already satisfied: datasets in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (4.8.4)
Requirement already satisfied: filelock in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (3.29.4)
Requirement already satisfied: numpy>=1.17 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (2.5.2)
Requirement already satisfied: pyarrow>=21.0.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (3.0.5)
Requirement already satisfied: requests>=2.32.2 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (4.70.0)
Requirement already satisfied: xxhash in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2026.2.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (1.15.0)
Requirement already satisfied: packaging in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (26.3)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.14.3)
Requirement already satisfied: anyio in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from httpx<1.0.0->datasets) (2026.7.22)
Requirement already satisfied: httpcore==1.* in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from httpx<1.0.0->datasets) (3.18)
Requirement already satisfied: h11>=0.16 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.4.3)
Requirement already satisfied: typer>=0.20.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.16.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.8.0)
Requirement already satisfied: propcache>=0.2.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from requests>=2.32.2->datasets) (2.7.0)
Requirement already satisfied: colorama in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: click>=8.2.1 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (8.5.0)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [3]:
# importing Libraries
import pandas as pd 
from datasets import load_dataset
import matplotlib.pyplot as plt 

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df=dataset['train'].to_pandas()

# Data Cleaning
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [4]:
df.loc[:, 'salary_rate':'salary_hour_avg'].dropna(subset='salary_rate')

       salary_rate  salary_year_avg  salary_hour_avg
28            year         109500.0              NaN
43            hour              NaN             97.5
51            hour              NaN             72.5
77            year         140000.0              NaN
92            year         120000.0              NaN
...            ...              ...              ...
785624        year         139216.0              NaN
785641        year         150000.0              NaN
785648        year         221875.0              NaN
785682        year         157500.0              NaN
785692        year         157500.0              NaN

[33067 rows x 3 columns]

## Select First 5 Rows with .iloc()

In [5]:
df.iloc[0:5, [1, 2]]

,job_title,job_location
0,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT"
1,Data Analyst,"Guadalajara, Jalisco, Mexico"
2,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany"
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX"
4,Data Engineer- Sr Jobs,"Washington, DC"

## Get Rows and Columns with .loc()

In [6]:
df.columns.get_loc('job_title')

1

In [7]:
df.columns.get_loc('job_posted_date')

7

In [8]:
df.iloc[5:10, 1:7]

,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location
5,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia
6,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States"
7,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania
8,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark
9,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States"

## First 15 Rows in US

In [9]:
#df.columns.get_loc('job_title')

df.columns.get_loc('salary_year_avg')

12

In [10]:
df.loc[:15, 'job_title':'salary_year_avg']

,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg
0,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN
1,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN
2,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN
4,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN
5,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN
6,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN
7,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49,False,False,Romania,NaN,NaN
8,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34,False,False,Denmark,NaN,NaN
9,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN
10,Erfahrene*r Data Engineer*in (m/w/d),"Basel, Switzerland",via LinkedIn,Full-time,False,Switzerland,2023-04-17 13:27:32,True,False,Switzerland,NaN,NaN
11,Data Engineer,"Colorado Springs, CO (+3 others)",via The Muse,Full-time,False,"Texas, United States",2023-11-03 13:06:51,False,True,United States,NaN,NaN
12,Stagiaire Data Analyst (H/F) - Lyon (69006),"Lyon, France",via Jobijoba,Full-time and Internship,False,France,2023-12-22 13:24:41,False,False,France,NaN,NaN
13,Senior Data Engineer,"New York, NY",via LinkedIn,Full-time,False,"Texas, United States",2023-11-15 13:08:52,True,True,United States,NaN,NaN
14,Data Engineer,"Rio de Janeiro, State of Rio de Janeiro, Brazil",via BeBee,Full-time,False,Brazil,2023-07-13 13:17:51,False,False,Brazil,NaN,NaN
15,Data Engineer,"Aberdeen, UK",via LinkedIn,Temp work,False,United Kingdom,2023-10-19 13:37:16,False,False,United Kingdom,NaN,NaN

In [11]:
df_US = df[df['job_country'] == 'United States']
df_US[['job_title', 'salary_year_avg']].iloc[:15]

                                            job_title  salary_year_avg
0   Senior Clinical Data Engineer / Principal Clin...              NaN
3   LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...              NaN
5                                   GCP Data Engineer              NaN
6                   Senior Data Engineer  - GCP Cloud              NaN
9                                   Data Scientist II              NaN
11                                      Data Engineer              NaN
13                               Senior Data Engineer              NaN
17                             Data Science Team Lead              NaN
26                                      Data Engineer              NaN
27  Principal Data Engineer (Lead), Knowledge Grap...              NaN
30     Senior Data Engineer (Work from home Eligible)              NaN
32   Sr. Data Scientist (NLP) - Full-time / Part-time              NaN
35                        Data Engineer - Royal Canin              NaN
36                                       Data Analyst              NaN
37                     Data Engineer III - Now Hiring              NaN

## Filter by Date

In [18]:
df.loc[
    df['job_posted_date'] > '2023-05-01',
    ['job_title', 'job_location', 'job_posted_date']
]

,job_title,job_location,job_posted_date
0,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",2023-06-16 13:44:15
2,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",2023-10-10 13:14:55
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",2023-07-04 13:01:41
4,Data Engineer- Sr Jobs,"Washington, DC",2023-08-07 14:29:36
5,GCP Data Engineer,Anywhere,2023-11-07 14:01:59
...,...,...,...
785694,Data Engineer,"Graz, Austria",2023-05-07 07:07:37
785696,Senior Analytics Engineer,"Colombia, Huila, Colombia",2023-10-23 06:31:25
785698,"Data Engineer, Gerencia Business Intelligence","Las Condes, Chile",2023-08-09 06:32:00
785701,"Data Engineer, Gerencia Business Intelligence","Santiago, Chile",2023-08-09 06:31:57
785706,Junior Data Engineer,"Lima, Peru",2023-11-08 06:34:48