# Pandas Data Cleaning

In [2]:
!pip install datasets

Requirement already satisfied: datasets in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (4.8.4)
Requirement already satisfied: filelock in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (3.29.4)
Requirement already satisfied: numpy>=1.17 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (2.5.2)
Requirement already satisfied: pyarrow>=21.0.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (3.0.5)
Requirement already satisfied: requests>=2.32.2 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (4.70.0)
Requirement already satisfied: xxhash in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2026.2.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (1.15.0)
Requirement already satisfied: packaging in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (26.3)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.14.3)
Requirement already satisfied: anyio in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from httpx<1.0.0->datasets) (2026.7.22)
Requirement already satisfied: httpcore==1.* in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from httpx<1.0.0->datasets) (3.18)
Requirement already satisfied: h11>=0.16 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.4.3)
Requirement already satisfied: typer>=0.20.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.16.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.8.0)
Requirement already satisfied: propcache>=0.2.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from requests>=2.32.2->datasets) (2.7.0)
Requirement already satisfied: colorama in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: click>=8.2.1 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (8.5.0)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\User\miniconda3\envs\python_course\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [3]:
# importing Libraries
import pandas as pd 
from datasets import load_dataset
import matplotlib.pyplot as plt 

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df=dataset['train'].to_pandas()

# Data Cleaning
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

# pandas.DataFrame.fillna
### DataFrame.fillna(value, *, axis=None, inplace=False, limit=None)

#### fillna() → Fill missing values

In [ ]:
df.loc[:10, 'salary_year_avg':'salary_hour_avg']

   salary_year_avg  salary_hour_avg
0              NaN              NaN
1              NaN              NaN
2              NaN              NaN
3              NaN              NaN
4              NaN              NaN
5              NaN              NaN
6              NaN              NaN
7              NaN              NaN
8              NaN              NaN
9              NaN              NaN

In [11]:
median_salary_year = df['salary_year_avg'].median()

In [14]:
median_salary_hour = df['salary_hour_avg'].median()

In [23]:
df_filled = df

df_filled['salary_year_avg'] = df_filled['salary_year_avg'].fillna(median_salary_year)
df_filled['salary_hour_avg'] = df_filled['salary_hour_avg'].fillna(median_salary_hour).round(2)

In [24]:
df_filled.loc[:10, 'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0          115000.0            45.98
1          115000.0            45.98
2          115000.0            45.98
3          115000.0            45.98
4          115000.0            45.98
5          115000.0            45.98
6          115000.0            45.98
7          115000.0            45.98
8          115000.0            45.98
9          115000.0            45.98
10         115000.0            45.98

# pandas.DataFrame.drop_duplicates
### DataFrame.drop_duplicates(subset=None, *, keep='first', inplace=False, ignore_index=False)

In [27]:
df_unique = df_filled

df_unique = df_unique.drop_duplicates()

print('Length of orginal df:           ', len(df_filled))
print('Length of drop duplicateds df:', len(df_unique))
print('Row Dropped:                 ', len(df_filled)-len(df_unique))

Length of orginal df:            785741
Length of drop duplicateds df: 785640
Row Dropped:                  101

In [28]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,115000.0,45.98,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,115000.0,45.98,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,115000.0,45.98,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,115000.0,45.98,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,115000.0,45.98,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,115000.0,45.98,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,115000.0,45.98,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,115000.0,45.98,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,115000.0,45.98,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,115000.0,45.98,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [29]:
df_unique = df_unique.drop_duplicates(subset=['job_title', 'company_name'])
print('Length of orginal df:           ', len(df_filled))
print('Length of drop duplicateds df:', len(df_unique))
print('Row Dropped:                 ', len(df_filled)-len(df_unique))

Length of orginal df:            785741
Length of drop duplicateds df: 508042
Row Dropped:                  277699

## Remove Rows with Missing Values

#### dropna() → Remove missing values

In [31]:
rows_before = len(df)
df_cleaned = df.dropna(subset= ['salary_year_avg'])
rows_after= len(df_cleaned)

rows_before, rows_after

(785741, 785741)

## Remove Duplicate Rows

In [ ]:
#rows_before = len(df)
#df_cleaned = df.drop_duplicates(subset = ['job_location'])
#rows_after = len(df_cleaned)

rows_before = df.shape[0]
df_unique = df.drop_duplicates(subset = ['job_location'])
rows_after = df_unique.shape[0]
rows_before, rows_after

(785741, 17218)

### Fill Missing Values in Column

In [35]:
salary_rate_before = df['salary_rate'].head(10)
df_filled = df.fillna({'salary_rate': 'Unknown'})
salary_rate_after = df_filled['salary_rate'].head(10)

salary_rate_before, salary_rate_after

(0    NaN
 1    NaN
 2    NaN
 3    NaN
 4    NaN
 5    NaN
 6    NaN
 7    NaN
 8    NaN
 9    NaN
 Name: salary_rate, dtype: str,
 0    Unknown
 1    Unknown
 2    Unknown
 3    Unknown
 4    Unknown
 5    Unknown
 6    Unknown
 7    Unknown
 8    Unknown
 9    Unknown
 Name: salary_rate, dtype: str)